# Generated by Django 3.2.11 on 2022-01-27 11:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('udaya_rana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=100000)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=500)),
                ('order_by', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('caption', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=500)),
                ('order_by', models.IntegerField(blank=True, default=0)),
                ('featured', models.IntegerField(blank=True, default=0)),
                ('album_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.album')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='telephone',
        ),
    ]
