# Generated by Django 3.2.11 on 2022-01-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0003_auto_20220127_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
