# Generated by Django 3.2.11 on 2022-01-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0005_auto_20220127_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.video_category'),
        ),
    ]
