# Generated by Django 3.2.11 on 2022-01-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0007_alter_video_video_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.video_category'),
        ),
    ]
