# Generated by Django 3.2.11 on 2022-01-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0009_article_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('dob', models.DateField(blank=True)),
                ('address', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated',
        ),
        migrations.CreateModel(
            name='Work_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=1000)),
                ('role', models.TextField()),
                ('description', models.TextField()),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1000)),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Political_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='International_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('acadamic_level', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=1000)),
                ('role', models.TextField()),
                ('description', models.TextField()),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
    ]
