# Generated by Django 3.2.11 on 2022-01-28 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0010_auto_20220128_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=1000)),
                ('bio_data', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='udaya_rana.bio_data')),
            ],
        ),
    ]
