# Generated by Django 3.2.11 on 2022-01-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0013_alter_bio_data_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_data',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
