# Generated by Django 3.2.11 on 2022-01-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0015_alter_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
