# Generated by Django 3.2.11 on 2022-01-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0017_bio_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('hide', 'HIDE')], default='active', max_length=500),
        ),
    ]
