# Generated by Django 3.2.11 on 2022-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0018_auto_20220129_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='active',
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('hide', 'HIDE')], default='active', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('hide', 'HIDE')], default='active', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('hide', 'HIDE')], default='active', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('hide', 'HIDE')], default='active', max_length=500),
        ),
    ]
