# Generated by Django 3.2.11 on 2022-01-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0019_auto_20220129_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='order_by',
        ),
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='image',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='order_by',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(default='background.jpg', max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(default='background.jpg', max_length=1000, upload_to=''),
        ),
    ]
