# Generated by Django 3.2.11 on 2022-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0021_auto_20220129_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
