# Generated by Django 3.2.11 on 2022-01-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0022_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
