# Generated by Django 3.2.11 on 2022-01-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0023_alter_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_category',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='video_category',
            name='updated',
        ),
    ]
