# Generated by Django 3.2.11 on 2022-01-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0024_auto_20220129_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_category',
            name='cover_image',
            field=models.FileField(default='profile.jpg', max_length=1000, upload_to=''),
        ),
    ]
