# Generated by Django 3.2.11 on 2022-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0025_alter_video_category_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_category',
            name='cover_image',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
