# Generated by Django 3.2.11 on 2022-01-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0026_alter_video_category_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_category_id',
            new_name='video_category',
        ),
    ]
