# Generated by Django 3.2.11 on 2022-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0027_auto_20220129_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='featured',
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Insert embeded link only'),
        ),
    ]
