# Generated by Django 3.2.11 on 2022-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0028_auto_20220129_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_data',
            name='dob',
            field=models.DateField(blank=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='bio_data',
            name='image',
            field=models.CharField(default='None', max_length=1000, verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Link [Embeded link only]'),
        ),
    ]
