# Generated by Django 3.2.11 on 2022-01-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0030_alter_bio_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_data',
            name='image',
            field=models.FileField(max_length=1000, upload_to='', verbose_name='Profile picture'),
        ),
    ]
