# Generated by Django 3.2.11 on 2022-01-30 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0032_auto_20220129_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivements_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('count', models.CharField(max_length=1000, verbose_name='Number of achievements')),
                ('icon', models.CharField(choices=[('award_fill', '<i class="bi bi-award-fill"></i>'), ('check_square_fill', '<i class="bi bi-check-square-fill"></i>'), ('award_fill', '<i class="bi bi-award-fill"></i>'), ('award_fill', '<i class="bi bi-award-fill"></i>'), ('award_fill', '<i class="bi bi-award-fill"></i>')], default='award_fill', max_length=500)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('hide', 'HIDE')], default='active', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='', verbose_name='Slider image')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('hide', 'HIDE')], default='active', max_length=500)),
            ],
        ),
    ]
