# Generated by Django 3.2.11 on 2022-01-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0039_alter_achivements_counter_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivements_counter',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
