# Generated by Django 3.2.11 on 2022-01-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0040_alter_achivements_counter_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivements_counter',
            name='count',
            field=models.IntegerField(max_length=1000, verbose_name='Number of achievements'),
        ),
    ]
