# Generated by Django 3.2.11 on 2022-01-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0042_alter_achivements_counter_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achivements_counter',
            old_name='icon',
            new_name='image',
        ),
    ]
