# Generated by Django 3.2.11 on 2022-01-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0043_rename_icon_achivements_counter_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivements_counter',
            new_name='Achievements_counter',
        ),
    ]
