# Generated by Django 3.2.11 on 2022-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaya_rana', '0046_mainmenu_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu_background',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('hide', 'HIDE')], default='active', max_length=500),
        ),
    ]
